### ISSUE TITLE
Fix EC2 auto deploy

### ISSUE THREAD

**Issue by SanjinDedic** [SanjinDedic/agent_games#63]
1. remove all pm 2 refs
2. fix paths (root) 
3. change to update systemd name
4. CAn we make the actions script FAIL when the pull fails!!

**Comment by DawoodLaiq** [comment]
Fixed uploading to the agent games ec2.
agent_games folder gets created and all the contents of backend are copied to that folder.
Local docker image is created and the service is restarted.

One thing need to be checked is that if the ec2 is brand new then server setups are not done then the service would not run because venv wouldn't be created.

**Comment by SanjinDedic** [comment]
thank you good work
